### ISSUE TITLE
New release for ESLint 2.0 compatibility

### ISSUE THREAD

**Issue by jaythomas** [mattlewis92/eslint-config-mwl#1]
Hey, I'm a big fan of your config and find it quite convenient to install as a node package. Could I get a version bump with a dependency on 2.x versions of ESLint? Thanks!

**Comment by mattlewis92** [comment]
Hey Jay,

0.4.0 already has this 😀

Although I'm probably going to deprecate this module soon in favour of this config as its better maintained, and has more of the latest rules enabled:
https://www.npmjs.com/package/eslint-config-xo-space

**Comment by jaythomas** [comment]
Thanks for the info and apologies as I didn't see the version bump until now. That config looks pretty interesting and I like that it's sub-divided into extensions as well. Closing this issue!

**Comment by mattlewis92** [comment]
No worries, hope everything is going well at singlecomm for you guys 😀
